//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aqua.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aqua.Extensions.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about one day.
        /// </summary>
        internal static string RoundTimeAboutOneDay {
            get {
                return ResourceManager.GetString("RoundTimeAboutOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about one hour.
        /// </summary>
        internal static string RoundTimeAboutOneHour {
            get {
                return ResourceManager.GetString("RoundTimeAboutOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about one minute.
        /// </summary>
        internal static string RoundTimeAboutOneMinute {
            get {
                return ResourceManager.GetString("RoundTimeAboutOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} days.
        /// </summary>
        internal static string RoundTimeDays {
            get {
                return ResourceManager.GetString("RoundTimeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} hours.
        /// </summary>
        internal static string RoundTimeHours {
            get {
                return ResourceManager.GetString("RoundTimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a minute.
        /// </summary>
        internal static string RoundTimeLessThanAMinute {
            get {
                return ResourceManager.GetString("RoundTimeLessThanAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} minutes.
        /// </summary>
        internal static string RoundTimeTotalMinutes {
            get {
                return ResourceManager.GetString("RoundTimeTotalMinutes", resourceCulture);
            }
        }
    }
}
