// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Corvus.Extensions.Specs.TraversalExtensionsFeatures
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TraversalExtensions")]
    public partial class TraversalExtensionsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TraversalExtensions.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "TraversalExtensions", "\tIn order to manipulate enumerations\r\n\tAs a developer\r\n\tI want a variety of Linq " +
                    "extensions", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreach")]
        public virtual void ACollectionIsEnumeratedWithForeach()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreach", null, ((string[])(null)));
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table71.AddRow(new string[] {
                        "1",
                        "1"});
            table71.AddRow(new string[] {
                        "1",
                        "2"});
            table71.AddRow(new string[] {
                        "1",
                        "3"});
            table71.AddRow(new string[] {
                        "1",
                        "4"});
            table71.AddRow(new string[] {
                        "1",
                        "5"});
#line 7
 testRunner.Given("the following collections", ((string)(null)), table71, "Given ");
#line 14
 testRunner.When("I enumerate collection 1 with foreach add to another collection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then("Collection 2 should match Collection 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreach with no action")]
        public virtual void ACollectionIsEnumeratedWithForeachWithNoAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreach with no action", null, ((string[])(null)));
#line 17
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table72.AddRow(new string[] {
                        "1",
                        "1"});
            table72.AddRow(new string[] {
                        "1",
                        "2"});
            table72.AddRow(new string[] {
                        "1",
                        "3"});
            table72.AddRow(new string[] {
                        "1",
                        "4"});
            table72.AddRow(new string[] {
                        "1",
                        "5"});
#line 18
 testRunner.Given("the following collections", ((string)(null)), table72, "Given ");
#line 25
 testRunner.When("I enumerate collection 1 with foreach with no action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.Then("an ArgumentNullException should be thrown for parameter \"onNext\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachatindex")]
        public virtual void ACollectionIsEnumeratedWithForeachatindex()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachatindex", null, ((string[])(null)));
#line 28
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table73 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table73.AddRow(new string[] {
                        "1",
                        "1"});
            table73.AddRow(new string[] {
                        "1",
                        "2"});
            table73.AddRow(new string[] {
                        "1",
                        "3"});
            table73.AddRow(new string[] {
                        "1",
                        "4"});
            table73.AddRow(new string[] {
                        "1",
                        "5"});
#line 29
 testRunner.Given("the following collections", ((string)(null)), table73, "Given ");
#line 36
 testRunner.When("I enumerate collection 1 with foreachatindex add to another collection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.Then("Collection 2 should match Collection 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 38
 testRunner.And("each index should be passed in order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachatindex with no action")]
        public virtual void ACollectionIsEnumeratedWithForeachatindexWithNoAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachatindex with no action", null, ((string[])(null)));
#line 40
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table74 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table74.AddRow(new string[] {
                        "1",
                        "1"});
            table74.AddRow(new string[] {
                        "1",
                        "2"});
            table74.AddRow(new string[] {
                        "1",
                        "3"});
            table74.AddRow(new string[] {
                        "1",
                        "4"});
            table74.AddRow(new string[] {
                        "1",
                        "5"});
#line 41
 testRunner.Given("the following collections", ((string)(null)), table74, "Given ");
#line 48
 testRunner.When("I enumerate collection 1 with foreachatindex with no action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("an ArgumentNullException should be thrown for parameter \"action\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachfailend")]
        public virtual void ACollectionIsEnumeratedWithForeachfailend()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachfailend", null, ((string[])(null)));
#line 51
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table75 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table75.AddRow(new string[] {
                        "1",
                        "1"});
            table75.AddRow(new string[] {
                        "1",
                        "2"});
            table75.AddRow(new string[] {
                        "1",
                        "3"});
            table75.AddRow(new string[] {
                        "1",
                        "4"});
            table75.AddRow(new string[] {
                        "1",
                        "5"});
#line 52
 testRunner.Given("the following collections", ((string)(null)), table75, "Given ");
#line 59
 testRunner.When("I enumerate collection 1 with foreachfailend add to another collection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
 testRunner.Then("Collection 2 should match Collection 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachfailend with a failing action")]
        public virtual void ACollectionIsEnumeratedWithForeachfailendWithAFailingAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachfailend with a failing action", null, ((string[])(null)));
#line 62
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table76 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table76.AddRow(new string[] {
                        "1",
                        "1"});
            table76.AddRow(new string[] {
                        "1",
                        "2"});
            table76.AddRow(new string[] {
                        "1",
                        "3"});
            table76.AddRow(new string[] {
                        "1",
                        "4"});
            table76.AddRow(new string[] {
                        "1",
                        "5"});
#line 63
 testRunner.Given("the following collections", ((string)(null)), table76, "Given ");
#line 70
 testRunner.When("I enumerate collection 1 with foreachfailend with a failing action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
 testRunner.Then("an Aggregate exception should be thrown containing 5 \"InvalidOperationException\" " +
                    "instances", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachfailend with no action")]
        public virtual void ACollectionIsEnumeratedWithForeachfailendWithNoAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachfailend with no action", null, ((string[])(null)));
#line 73
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table77 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table77.AddRow(new string[] {
                        "1",
                        "1"});
            table77.AddRow(new string[] {
                        "1",
                        "2"});
            table77.AddRow(new string[] {
                        "1",
                        "3"});
            table77.AddRow(new string[] {
                        "1",
                        "4"});
            table77.AddRow(new string[] {
                        "1",
                        "5"});
#line 74
 testRunner.Given("the following collections", ((string)(null)), table77, "Given ");
#line 81
 testRunner.When("I enumerate collection 1 with foreachfailend with no action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 82
 testRunner.Then("an ArgumentNullException should be thrown for parameter \"action\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A null collection is enumerated with foreach")]
        public virtual void ANullCollectionIsEnumeratedWithForeach()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A null collection is enumerated with foreach", null, ((string[])(null)));
#line 84
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 85
 testRunner.When("I enumerate a null collection with foreach", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
 testRunner.Then("an ArgumentNullException should be thrown for parameter \"source\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A null collection is enumerated with foreachfailend")]
        public virtual void ANullCollectionIsEnumeratedWithForeachfailend()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A null collection is enumerated with foreachfailend", null, ((string[])(null)));
#line 88
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 89
 testRunner.When("I enumerate a null collection with foreachfailend", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
 testRunner.Then("a NullReferenceException should be thrown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A null collection is enumerated with foreachatindex")]
        public virtual void ANullCollectionIsEnumeratedWithForeachatindex()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A null collection is enumerated with foreachatindex", null, ((string[])(null)));
#line 92
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 93
 testRunner.When("I enumerate a null collection with foreachatindex", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 94
 testRunner.Then("a NullReferenceException should be thrown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("An integer range is generated")]
        public virtual void AnIntegerRangeIsGenerated()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("An integer range is generated", null, ((string[])(null)));
#line 96
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table78 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table78.AddRow(new string[] {
                        "1",
                        "1"});
            table78.AddRow(new string[] {
                        "1",
                        "2"});
            table78.AddRow(new string[] {
                        "1",
                        "3"});
            table78.AddRow(new string[] {
                        "1",
                        "4"});
            table78.AddRow(new string[] {
                        "1",
                        "5"});
#line 97
 testRunner.Given("the following integer collections", ((string)(null)), table78, "Given ");
#line 104
 testRunner.When("I generate a range from 1 to 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 105
 testRunner.Then("The range should match collection 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachasync")]
        public virtual void ACollectionIsEnumeratedWithForeachasync()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachasync", null, ((string[])(null)));
#line 107
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table79 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table79.AddRow(new string[] {
                        "1",
                        "1"});
            table79.AddRow(new string[] {
                        "1",
                        "2"});
            table79.AddRow(new string[] {
                        "1",
                        "3"});
            table79.AddRow(new string[] {
                        "1",
                        "4"});
            table79.AddRow(new string[] {
                        "1",
                        "5"});
#line 108
 testRunner.Given("the following collections", ((string)(null)), table79, "Given ");
#line 115
 testRunner.When("I enumerate collection 1 with foreachasync add to another collection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 116
 testRunner.Then("Collection 2 should match Collection 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachasync with no action")]
        public virtual void ACollectionIsEnumeratedWithForeachasyncWithNoAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachasync with no action", null, ((string[])(null)));
#line 118
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table80 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table80.AddRow(new string[] {
                        "1",
                        "1"});
            table80.AddRow(new string[] {
                        "1",
                        "2"});
            table80.AddRow(new string[] {
                        "1",
                        "3"});
            table80.AddRow(new string[] {
                        "1",
                        "4"});
            table80.AddRow(new string[] {
                        "1",
                        "5"});
#line 119
 testRunner.Given("the following collections", ((string)(null)), table80, "Given ");
#line 126
 testRunner.When("I enumerate collection 1 with foreachasync with no action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 127
 testRunner.Then("an ArgumentNullException should be thrown for parameter \"action\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A null collection is enumerated with foreachasync")]
        public virtual void ANullCollectionIsEnumeratedWithForeachasync()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A null collection is enumerated with foreachasync", null, ((string[])(null)));
#line 129
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 130
 testRunner.When("I enumerate a null collection with foreachasync", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 131
 testRunner.Then("a NullReferenceException should be thrown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachfailendasync")]
        public virtual void ACollectionIsEnumeratedWithForeachfailendasync()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachfailendasync", null, ((string[])(null)));
#line 133
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table81 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table81.AddRow(new string[] {
                        "1",
                        "1"});
            table81.AddRow(new string[] {
                        "1",
                        "2"});
            table81.AddRow(new string[] {
                        "1",
                        "3"});
            table81.AddRow(new string[] {
                        "1",
                        "4"});
            table81.AddRow(new string[] {
                        "1",
                        "5"});
#line 134
 testRunner.Given("the following collections", ((string)(null)), table81, "Given ");
#line 141
 testRunner.When("I enumerate collection 1 with foreachfailendasync add to another collection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 142
 testRunner.Then("Collection 2 should match Collection 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachfailendasync with a failing action")]
        public virtual void ACollectionIsEnumeratedWithForeachfailendasyncWithAFailingAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachfailendasync with a failing action", null, ((string[])(null)));
#line 144
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table82 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table82.AddRow(new string[] {
                        "1",
                        "1"});
            table82.AddRow(new string[] {
                        "1",
                        "2"});
            table82.AddRow(new string[] {
                        "1",
                        "3"});
            table82.AddRow(new string[] {
                        "1",
                        "4"});
            table82.AddRow(new string[] {
                        "1",
                        "5"});
#line 145
 testRunner.Given("the following collections", ((string)(null)), table82, "Given ");
#line 152
 testRunner.When("I enumerate collection 1 with foreachfailendasync with a failing action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 153
 testRunner.Then("an Aggregate exception should be thrown containing 5 \"InvalidOperationException\" " +
                    "instances", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachfailendasync with no action")]
        public virtual void ACollectionIsEnumeratedWithForeachfailendasyncWithNoAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachfailendasync with no action", null, ((string[])(null)));
#line 155
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table83 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table83.AddRow(new string[] {
                        "1",
                        "1"});
            table83.AddRow(new string[] {
                        "1",
                        "2"});
            table83.AddRow(new string[] {
                        "1",
                        "3"});
            table83.AddRow(new string[] {
                        "1",
                        "4"});
            table83.AddRow(new string[] {
                        "1",
                        "5"});
#line 156
 testRunner.Given("the following collections", ((string)(null)), table83, "Given ");
#line 163
 testRunner.When("I enumerate collection 1 with foreachfailendasync with no action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 164
 testRunner.Then("an ArgumentNullException should be thrown for parameter \"action\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A null collection is enumerated with foreachfailendasync")]
        public virtual void ANullCollectionIsEnumeratedWithForeachfailendasync()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A null collection is enumerated with foreachfailendasync", null, ((string[])(null)));
#line 166
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 167
 testRunner.When("I enumerate a null collection with foreachfailendasync", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 168
 testRunner.Then("a NullReferenceException should be thrown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachatindexasync")]
        public virtual void ACollectionIsEnumeratedWithForeachatindexasync()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachatindexasync", null, ((string[])(null)));
#line 171
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table84 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table84.AddRow(new string[] {
                        "1",
                        "1"});
            table84.AddRow(new string[] {
                        "1",
                        "2"});
            table84.AddRow(new string[] {
                        "1",
                        "3"});
            table84.AddRow(new string[] {
                        "1",
                        "4"});
            table84.AddRow(new string[] {
                        "1",
                        "5"});
#line 172
 testRunner.Given("the following collections", ((string)(null)), table84, "Given ");
#line 179
 testRunner.When("I enumerate collection 1 with foreachatindexasync add to another collection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 180
 testRunner.Then("Collection 2 should match Collection 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 181
 testRunner.And("each index should be passed in order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A collection is enumerated with foreachatindexasync with no action")]
        public virtual void ACollectionIsEnumeratedWithForeachatindexasyncWithNoAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A collection is enumerated with foreachatindexasync with no action", null, ((string[])(null)));
#line 183
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table85 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection",
                        "Value"});
            table85.AddRow(new string[] {
                        "1",
                        "1"});
            table85.AddRow(new string[] {
                        "1",
                        "2"});
            table85.AddRow(new string[] {
                        "1",
                        "3"});
            table85.AddRow(new string[] {
                        "1",
                        "4"});
            table85.AddRow(new string[] {
                        "1",
                        "5"});
#line 184
 testRunner.Given("the following collections", ((string)(null)), table85, "Given ");
#line 191
 testRunner.When("I enumerate collection 1 with foreachatindexasync with no action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 192
 testRunner.Then("an ArgumentNullException should be thrown for parameter \"action\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A null collection is enumerated with foreachatindexasync")]
        public virtual void ANullCollectionIsEnumeratedWithForeachatindexasync()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A null collection is enumerated with foreachatindexasync", null, ((string[])(null)));
#line 194
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 195
 testRunner.When("I enumerate a null collection with foreachatindexasync", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 196
 testRunner.Then("a NullReferenceException should be thrown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When you merge two dictionaries")]
        public virtual void WhenYouMergeTwoDictionaries()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When you merge two dictionaries", null, ((string[])(null)));
#line 199
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table86 = new TechTalk.SpecFlow.Table(new string[] {
                        "Dictionary",
                        "Key",
                        "Value"});
            table86.AddRow(new string[] {
                        "1",
                        "1",
                        "3"});
            table86.AddRow(new string[] {
                        "1",
                        "4",
                        "1"});
            table86.AddRow(new string[] {
                        "1",
                        "5",
                        "2"});
            table86.AddRow(new string[] {
                        "2",
                        "1",
                        "1"});
            table86.AddRow(new string[] {
                        "2",
                        "2",
                        "3"});
            table86.AddRow(new string[] {
                        "2",
                        "3",
                        "5"});
            table86.AddRow(new string[] {
                        "2",
                        "4",
                        "3"});
            table86.AddRow(new string[] {
                        "3",
                        "1",
                        "1"});
            table86.AddRow(new string[] {
                        "3",
                        "2",
                        "3"});
            table86.AddRow(new string[] {
                        "3",
                        "3",
                        "5"});
            table86.AddRow(new string[] {
                        "3",
                        "4",
                        "3"});
            table86.AddRow(new string[] {
                        "3",
                        "5",
                        "2"});
#line 200
 testRunner.Given("the following dictionaries", ((string)(null)), table86, "Given ");
#line 214
 testRunner.When("I merge Dictionary 1 with Dictionary 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 215
 testRunner.Then("Dictionary 2 should equal Dictionary 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
